In [42]:
import numpy as np

def display(board):
    n = len(board)
    display = np.zeros([n,n])
    for i in range(n):
        for j in range(n):
            if board[i][j] == True:
                display[i][j] = 1
    print(display)

def isSafe(board, row, col):
    # Check vertical row
    for i in range(row):
        if board[i][col]:
            return False
        
    # Check diagonal left
    maxLeft = min(row, col)
    for i in range(1,maxLeft+1):
        if board[row-i][col-i]:
            return False
        
    # Check diagonal right
    maxRight = min(row, len(board) - col - 1)
    for i in range(1,maxRight+1):
        if board[row-i][col+i]:
            return False
        
    return True


def queens(board, row):
    if row == len(board):
        display(board)
        print("")
        return 1
    
    count = 0
    
    # Placing the queen and checking for every row and col
    for col in range(len(board)):
        # Place the queen if it is safe
        if isSafe(board, row, col):
            board[row][col] = True
            count += queens(board, row + 1)
            board[row][col] = False
        
    return count


n = 5
board = []
for i in range(n):
    board.append([])
    for j in range(n):
        board[i].append(False)
        
queens(board,0)

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]

[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]

[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]



10